name: release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        make install
    - name: Test with pytest
      run: |
        make test
    - name: Build
      run: |
        make build
    - name: set pypi release version
      run: |
        RELEASE_VERSION="$(git for-each-ref refs/tags --sort=-taggerdate --format='%(refname:short)' --count=1 2>&1)"
        git tag -a $RELEASE_VERSION -m ''
    - name: Publish package
      run: |
        export TWINE_USERNAME="${{secrets.PYPI_USER}}"
        export TWINE_PASSWORD="${{secrets.PYPI_PASSWORD}}"
        export TWINE_NON_INTERACTIVE=true
        twine upload dist/*
